spring:
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    url: jdbc:h2:mem:test
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
#        show_sql: true # sout 으로 찍음 , hibernate.SQL은 log로 찍음
        format_sql: true

logging.level:
  org.hibernate.SQL: debug
  org.hibernate.type: trace
